version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.15

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run:
          name: go build
          command: |-
            mkdir -p bin
            cd docker/src/cookie-shop-ci
            go build .
            cd -
            mv docker/src/cookie-shop-ci/cookie-shop-ci bin/
      - run:
          name: validate
          command: bin/cookie-shop-ci validate

workflows:
  build:
    jobs:
      - build

